name: client-c++

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services:
      model:
        image: linusseelinger/model-muq-beam:latest
        ports:
        - 4242:4242

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Dependencies
        run: |
          apt update; DEBIAN_FRONTEND="noninteractive" apt install -y g++
       -
        name: Build and run
        run: |
          cd testing/clients && g++ -std=c++17 test_c++.cc -pthread -I../../lib/ -o test_c++ && ./test_c++
