name: client-matlab

on:
  push:
  pull_request:
    branches:
      - 'main'
      
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      model:
        image: linusseelinger/benchmark-analytic-gaussian-mixture:latest
        ports:
        - 4243:4243

    steps:
      - uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run all tests
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: matlab; clients/matlab
