name: SLURM-LB

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: giovtorres/slurm-docker
      options: --cap-add sys_admin --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Check SLURM daemons are running
        run: |
         nohup /usr/local/bin/docker-entrypoint.sh > /tmp/entrypoint.log 2>&1 &
          for i in $(seq 1 60); do
            scontrol ping 2>/dev/null | grep -q UP && break
            sleep 5
          done
          
      - name: Clone UM-Bridge and run loadbalancer test
        run: |
         dnf -y install gcc-g++ libstdc++-static
         python3 -m venv venv && . venv/bin/activate && pip3 install umbridge
         git clone https://github.com/UM-Bridge/umbridge.git && cd umbridge/hpc && make 
         sed -i -e 's|--partition=devel|--partition=normal|' slurm_scripts/job.sh
         ./load-balancer --scheduler=slurm &
         sleep 20 && 
         python3 test/minimal/minimal-client.py